package com.bezukh.image_search.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
@Table(name = "image_documents")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Information about the uploaded image and its textual description")
public class ImageDocument {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Unique identifier in the database", example = "1")
    private Long id;

    @Column(nullable = false)
    @Schema(description = "Original name of the uploaded file", example = "my_dog.jpg")
    private String originalFileName;

    @Column(nullable = false, unique = true)
    @Schema(description = "Absolute or relative path to the file in the storage system", example = "./uploads/images/abc-123.jpg")
    private String storagePath;

    @Column(nullable = false, unique = true)
    @Schema(description = "Absolute or relative path to the thumbnail variant of file in the storage system", example = "./uploads/images/abc-123_thumb.jpg")
    private String thumbnailPath;

    @Column(columnDefinition = "TEXT")
    @Schema(description = "Description generated by the AI model (Computer Vision)", example = "A golden retriever playing with a ball in the park")
    private String aiDescription;

    @Schema(description = "Timestamp when the image was uploaded")
    private LocalDateTime uploadDate;

    @PrePersist
    protected void onCreate() {
        uploadDate = LocalDateTime.now();
    }
}